### ISSUE TITLE
Rename to "zeit/now" and create a monorepo

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2782]
As part of our effort of merging our codebases (Now CLI will invoke now-client, Now CLI will bundle & lock the default builders, they all need canary channels), we're going to merge all of the following repositories into a single one:

- https://github.com/zeit/now-cli
- https://github.com/zeit/now-builders
- https://github.com/zeit/now-client

In the near future, these packages should all live inside `zeit/now-cli` and the repo will be renamed to `zeit/now`.

### Tasks

- [x] Move `zeit/now-client` into `zeit/now-cli`
- [x] Move `zeit/now-builders` into `zeit/now-cli`
- [x] Set up Lerna with `canary` and `master`
- [x] Set up CI (new GitHub Actions if possible)
- [x] Merge monorepo to `master` #2812
- [x] Cherry pick monorepo commit to `canary` 229a62d8b6aeb1f5b19de71d4e7c8733ba9e310d
- [x] Rename `zeit/now-cli` to `zeit/now`
- [x] Transfer any open issues and PRs from `zeit/now-client` and `zeit/now-builders` to `zeit/now`
- [x] Archive `zeit/now-client` and `zeit/now-builders` and make the README point to the new `zeit/now`
- [x] Adjust all links across our system pointing to these repos https://github.com/zeit/docs/pull/1184
- [x] Cherry pick any missing PRs into `canary` [see example](https://stackoverflow.com/questions/42800902/git-generate-patch-for-all-commits-in-a-branch) #2884 #2880 #2883 #2885 #2881
- [x] Add GitHub Actions for publishing to npm #2891
- [x] Publish canary [16.1.3-canary.0](https://github.com/zeit/now/releases/tag/now%4016.1.3-canary.0)
- [x] Update readme of `zeit/now` to "The easiest way to deploy websites" (fix title) #2886
- [x] Unify linting & autoformatting #2914 
- [x] Update links to repos on https://zeit.co/oss

**Comment by borekb** [comment]
Do you guys have a workflow that you use for inspecting file history across repositories? It seems that all the files have been just copy-pasted, without maintaining Git history.

**Comment by leo** [comment]
@borekb Indeed. To make migrating easier, we've decided to retain the git history on their previous repositories. We're not using a special tool to do so, just the GitHub UI.

**Comment by borekb** [comment]
I remember doing a repo merge where Git history was maintained but it was a bit of an effort, I have to admit that 😄.

**Comment by styfle** [comment]
The builders only had about 6 months of git history so it wasn't a big loss. The history for `now-cli` is retained.

That being said, this checklist is complete!

**Comment by kidonng** [comment]
These repositories seem to be gone, not found under @vercel either:

https://github.com/zeit/now-builders
https://github.com/zeit/now-client

Particularly it means many contributors to zeit/now-builders, which contains various framework config presets, lost their attributions.

I'm not sure but it doesn't seem like the MIT license of the zeit/now-builders allows this. Could you please share the reason behind taking down those repositories?
